### PR TITLE
Scala 3.0.0-RC1, Scala.js 1.5.0

### PR DESCRIPTION
**Pull request by keynmol**

### CODE REVIEW

**Comment by kubukoz** [comment]
@eed3si9n can you make a release with this when you have some time? I think that's the last blocker for weaver to go to 3.0.0-RC1 :)

**Comment by keynmol** [comment]
We can actually make the release ourselves - I just wasn't sure if it should be 0.16.0 - I *think* Eugene increments minor version on each release of Scala 3?

**Comment by eed3si9n** [comment]
I normally try to:
1. backpublish using an existing version for Scala version bump
2. bump patch version if it's a bug fix
3. bump minor version if it adds some feature (that might require patch fix later)

**Comment by kubukoz** [comment]
I would definitely not introduce a new number for this, since it's a scala RC anyway - so 0.15.1_3.0.0-RC1?

**Comment by eed3si9n** [comment]
Yea. I've given @keynmol the power to cut a new release, but sbt-ci-release doesn't have a feature to back publish (via tag name convention etc). I've just back published 0.15.1 for Scala 3.0.0-RC1 and it's on its way to Maven Central.

**Comment by kubukoz** [comment]
Thank you!

**Comment by keynmol** [comment]
Going forward:

1. Binary and source compatible bugfixes get a patch version bump
2. Scala version bumps (2.12/2.13/3.x) get a patch version bump
3. Everything else gets a minor version bump (which subsumes the first two if they go out together), which is fine given expecty is 0.x right now.

Given that RC2 is probably imminent for Scala 3, we'll need to repeat this exercise soon, so I just want to make sure we're aligned and either @Baccata or I can release frequently.

@eed3si9n do you agree?

**Comment by kubukoz** [comment]
https://repo1.maven.org/maven2/com/eed3si9n/expecty/expecty_3.0.0-RC1/0.15.1/ is up!

**Comment by eed3si9n** [comment]
@keynmol Sounds good to me.

**Pull request merged**
