### PR TITLE
Scala 2.13.4 (was 2.13.3)

### PR DESCRIPTION
**Pull request by SethTisue**
opening the PR not because I intend to finish it myself, but to notify you of the test failures, which I also saw in the Scala community build

### CODE REVIEW

**Comment by eed3si9n** [comment]
@SethTisue Thanks Seth!

**Comment by keynmol** [comment]
I'm going to look into it.

Only culprit I can think of is `-Yrangepos` being on by default in 2.13.4. That said, I haven't yet found exactly the place where this takes effect.

Sadly I'll have to fix this as Native 0.4.0 just dropped and one of its components only published for 2.13.4 :D

**Comment by Baccata** [comment]
Tests are green, some behaviour in 2.13.4 around `List()` now aligns with 3.0.0-Mx for some reason. Because of this alignment, I'm choosing not to dive into the rabbit-hole of investigating the why.

**Review by eed3si9n — APPROVED** [review]

**Comment by SethTisue** [comment]
scala/community-build@fb0a4ded4abf86ad0c7867b6bb3bd76a01436b9a :+1:

**Pull request merged**
