### PR TITLE
Lintable expansion

### PR DESCRIPTION
**Pull request by som-snytt**
On 2.13.14, `-Wmacros:after -Xlint:missing-interpolator` will warn on the expanded assert that includes an interpolation.

Fix that by concatenating pieces of the string that represents the source text.

Also update dependencies, but run into trouble with 2.11.

A couple of tests require tweaked output because of how `List()` is rewritten to `Nil`. (The rewrite broke early in 2.13.x. I did not update Scala 3 or look into its behavior.)

Checked with local project that it passes lint and displays correctly
```
[error] assert(c.m == s"hello, $world")
[error]        | | |            |
[error]        | | false        hello, worldx
[error]        | hello, world
[error]        p.C@64687a13
```

### CODE REVIEW

**Comment by SethTisue** [comment]
@som-snytt should this still be "draft"...?

**Comment by som-snytt** [comment]
It says there is a problem on 2.11.x.

**Comment by SethTisue** [comment]
eh? checks are green

(regardless, I suspect Eugene would be open to a PR removing 2.11 from the crossbuild, at this point)

**Comment by som-snytt** [comment]
This comments out 2.11 ... sneaky! Amazing that sort of thing doesn't happen more often.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Pull request merged**
